feat: migrated from tauri to wails

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -3,145 +3,118 @@ on: [pull_request]
 
 jobs:
   build:
-    name: 🏗️ Build 
+    name: 🏗️ Build
     environment: test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-
-      - uses: pnpm/action-setup@v2
+      
+      - uses: ./.github/workflows/base-setup
         with:
-          version: 7
-
-      - uses: actions/setup-node@v3
-        with:
-          cache: 'pnpm'
-
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        shell: bash
-        run: |
-          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
-
-      - uses: actions/cache@v3
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-
-      - name: Install dependencies
-        run: pnpm install
+          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build
-        run: pnpm build
+        run: task frontend:build
 
-  unit-test:
-    name: 🧪 Unit Test
+  unit-test-go:
+    name: 🧪 Go:Unit Test
     runs-on: ubuntu-latest
+    permissions: write-all
     steps:
       - uses: actions/checkout@v3
-
-      - uses: pnpm/action-setup@v2
+      
+      - name: Set up Go
+        uses: actions/setup-go@v4
         with:
-          version: latest
+          go-version: 1.21
 
-      - uses: actions/setup-node@v3
+      - uses: ./.github/workflows/base-setup
         with:
-          cache: 'pnpm'
-
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        shell: bash
-        run: |
-          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
-
-      - uses: actions/cache@v3
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-
-      - name: Install dependencies
-        run: pnpm install
-
+          token: ${{ secrets.GITHUB_TOKEN }}
+ 
       - name: Test
-        run: pnpm test:unit
+        run: task go:test:unit
+  
+  unit-test-js:
+    name: 🧪 JS:Unit Test
+    runs-on: ubuntu-latest
+    permissions: write-all
+    steps:
+      - uses: actions/checkout@v3
+      
+      - uses: ./.github/workflows/base-setup
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+ 
+      - name: Test
+        run: task frontend:test:unit
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
+        if: success() || failure()
         with:
           name: 🧪 Vitest
-          path: results/*.xml
+          path: frontend/results/report.xml
+
           reporter: jest-junit
 
-  e2e-test:
-    name: 🧪 E2E Test
-    runs-on: ubuntu-latest
-    env:
-      NODE_ENV: testing
-    steps:
-      - uses: actions/checkout@v3
-
-      - uses: pnpm/action-setup@v2
+      - name: Code Coverage Report
+        if: success() || failure()
+        uses: irongut/CodeCoverageSummary@v1.3.0
         with:
-          version: latest
-      - uses: actions/setup-node@v3
+          filename: frontend/results/cobertura.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          output: both
+          thresholds: '60 80'
 
-      - name: Install dependencies
-        run: pnpm install
-
-      - name: Test E2E
-        run: pnpm test:e2e
-
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: success() || failure()
         with:
-          name: 🧪 Cypress
-          path: results/*.xml
-          reporter: jest-junit
+          recreate: true
+          path: code-coverage-results.md
+
+  # e2e-test:
+  #   name: 🧪 E2E Test
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     NODE_ENV: testing
+  #   steps:
+  #     - uses: actions/checkout@v3
+     
+  #     - uses: ./.github/workflows/base-setup
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+ 
+  #     - name: Test E2E
+  #       run: task frontend:test:e2e
+
+  #     - name: Test Report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure() # run this step even if previous step failed
+  #       with:
+  #         name: 🧪 Cypress
+  #         path: results/*.xml
+  #         reporter: jest-junit
 
   check:
     name: ✅ Check
+    environment: test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-
-      - uses: pnpm/action-setup@v2
+      
+      - uses: ./.github/workflows/base-setup
         with:
-          version: latest
-
-      - uses: actions/setup-node@v3
-        with:
-          cache: 'pnpm'
-
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        shell: bash
-        run: |
-          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
-
-      - uses: actions/cache@v3
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-
-      - name: Install dependencies
-        run: pnpm install
-
+          token: ${{ secrets.GITHUB_TOKEN }}
+ 
       - name: Setup matcher
         run: echo "::add-matcher::.github/actions/problemMatcher.json"
 
-      - name: Test
-        run: pnpm check
+      - name: Check
+        run: task frontend:check:ci
 
   lint:
     name: 🧹 Lint
@@ -150,15 +123,23 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - uses: pnpm/action-setup@v2
+      - uses: ./.github/workflows/base-setup
         with:
-          version: latest
-
-      - uses: actions/setup-node@v3
-        with:
-          cache: 'pnpm'
-
-      - run: pnpm install
-
+          token: ${{ secrets.GITHUB_TOKEN }}
+ 
       - name: Check lint
-        run: pnpm run lint
+        run: task frontend:lint
+  
+  bundle-size:
+    name: 📦 Bundle size
+    environment: test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: ./.github/workflows/base-setup
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+ 
+      - name: Check bundle size
+        run: task frontend:check:bundle
